var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/coursePage/[slug]/lessons/[lessonsSlug]/page.js")
R.c("server/chunks/ssr/_4ffce4c4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d0935222._.js")
R.c("server/chunks/ssr/_1b355fa1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__8756e439._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/[root-of-the-server]__666f8ec1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_layout_tsx_271801d7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/ce889_server_app_coursePage_[slug]_lessons_[lessonsSlug]_page_actions_829cbe5d.js")
R.m(60525)
module.exports=R.m(60525).exports
